version: '3.8'

services:
  # NGINX Reverse Proxy Container
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Path to your nginx configuration file
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
